[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    excludedPath = [
      "/dist/astro",
      "/dist/images",
      "*.css",
      "*.js",
      "*.svg",
      "*.txt",
      "*.xml",
    ]
    path = "/*"
    reportOnly = false
    unsafeEval = false
