[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "object-src 'none'; base-uri 'self'; require-trusted-types-for 'script';"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    excludedPath = [
      "/dist/astro",
      "/dist/images",
      "*.css",
      "*.js",
      "*.svg",
      "*.txt",
      "*.xml",
    ]
    path = "/*"
    reportOnly = false
    unsafeEval = false
