[dev]
    command = "npm run dev"
    framework = "#custom"
    targetPort = 4321

[build]
    command = "npm run build"
    publish = "dist"

[build.environment]
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    excludedPath = [
      "/dist/astro",
      "/dist/images",
      "*.css",
      "*.js",
      "*.svg",
      "*.txt",
      "*.xml",
    ]
    path = "/*"
    reportOnly = false
    unsafeEval = true

[[plugins]]
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        # run E2E tests against the deployed URL
        record = true
        group = 'deployed'

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "object-src 'none'; base-uri 'self';"
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'

[[edge_functions]]
  path = "/*"
  function = "csp-headers-for-html-only"

[[redirects]]
from = "/services/digital-sustainability/"
to = "/services/sustainable-digitalization/"
status = 301

[[redirects]]
from = "/de/services/digital-sustainability/"
to = "/de/services/sustainable-digitalization/"
status = 301
