[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "object-src 'none'; base-uri 'self';"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    excludedPath = [
      "/dist/astro",
      "/dist/images",
      "*.css",
      "*.js",
      "*.svg",
      "*.txt",
      "*.xml",
    ]
    path = "/*"
    reportOnly = false
    unsafeEval = false

[[edge_functions]]
  path = "/*"
  function = "csp-headers-for-html-only"
